language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
env:
    - TORNADO_VERSION=4.5.1 PYTEST=3.3.2
    - TORNADO_VERSION=4.5.2 PYTEST=3.3.2
    - TORNADO_VERSION=4.5.3 PYTEST=3.3.2
install:
    - pip install -q tornado==$TORNADO_VERSION pytest==$PYTEST_VERSION
    - python setup.py install
script:
    - pytest -sv
